### ISSUE TITLE
Icons are not visible in the select window

### ISSUE THREAD

**Issue by samah5751** [marshmallow-packages/nova-fontawesome#3]
![Screenshot 2022-08-13 at 21-40-21 Laravel - Create Test](https://user-images.githubusercontent.com/91948161/184503086-69274fb1-737b-4496-b177-b271e05a83dd.png)

![Screenshot from 2022-08-13 21-46-05](https://user-images.githubusercontent.com/91948161/184503285-cf37f00c-a5b0-49c6-ad4e-72210069d32c.png)

Does not load icons. I have downloaded fontawesome 6.0 and copied fontawesome.css to /public/css/ folder but it does not show any icons other than letters and numbers. I have tried copying all fontawesome assets to /public/css/ as well, but no luck. Am I doing something wrong?

**Comment by LTKort** [comment]
@samah5751 This could be an issue with the default asset url, we have changed & updated the package to look for the css in the asset folder.

It should work for version v2.0.6, if not please let us know
